### ISSUE TITLE
Pretrained Model Needed

### ISSUE THREAD

**Issue by sdogsq** [fizisist/LorentzGroupNetwork#5]
Hi authors,

I really appreciate this insightful work and innovative idea. Recently I am trying to reproduce the experiments in your paper. However, the model really needs plenty of times on training according to the settings (batchsize=8 , 53 epochs) in your paper.  I tried to increase the batchsize to 64 and reduce the epochs to 20, but the model cannot reach the best performance especially for $1/\epsilon_B$.   May I ask if by any chance you could provide me with the pretrained model or prediction results ( top.best.test.pt or best.test_ROC.csv) ? Thanks a lot!

Merry Christmas,
shiqi

**Comment by level1807** [comment]
Hi, I have added a few pretrained models in `models/pretrained`, check them out! Let me know if you have any other questions.

**Comment by level1807** [comment]
Actually let me backtrack since adding all these files to the repo isn't great. Here is a file with some pretrained models, their predictions, logs, and ROC curves.
[maxdim3_nobj126_lr1e-3_1e-7_lrdecay-exp_pt550-650_nepoch_100_data100_.zip](https://github.com/fizisist/LorentzGroupNetwork/files/7790021/maxdim3_nobj126_lr1e-3_1e-7_lrdecay-exp_pt550-650_nepoch_100_data100_.zip)

**Comment by abogatskiy** [comment]
Actually let me backtrack since adding all these files to the repo isn't great. Here is a file with some pretrained models, their predictions, logs, and ROC curves. Each run includes only the best model (which is not always the last).
[maxdim3_nobj126_lr1e-3_1e-7_lrdecay-exp_pt550-650_nepoch_100_data100_part1.zip](https://github.com/fizisist/LorentzGroupNetwork/files/7790146/maxdim3_nobj126_lr1e-3_1e-7_lrdecay-exp_pt550-650_nepoch_100_data100_part1.zip)
[maxdim3_nobj126_lr1e-3_1e-7_lrdecay-exp_pt550-650_nepoch_100_data100_part2.zip](https://github.com/fizisist/LorentzGroupNetwork/files/7790147/maxdim3_nobj126_lr1e-3_1e-7_lrdecay-exp_pt550-650_nepoch_100_data100_part2.zip)

**Comment by sdogsq** [comment]
Many Thanks! I fully understand your concern. These really help me a lot anyway.  :)
